# ===== BUILD STAGE =====
FROM node:22.11.0-alpine AS builder

WORKDIR /app

# คัดลอกไฟล์ package.json และ package-lock.json ก่อนเพื่อลด cache invalidation
COPY package.json package-lock.json ./
RUN npm ci

# คัดลอกโค้ดทั้งหมด
COPY . .

# สร้างไฟล์ Build ของ Next.js
RUN npm run build 

# ===== RUN STAGE =====
FROM node:22.11.0-alpine AS runner

WORKDIR /app

# คัดลอกเฉพาะไฟล์ที่จำเป็นจาก builder stage
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/.next /app/.next
COPY --from=builder /app/public /app/public
COPY --from=builder /app/node_modules /app/node_modules

# เปิด Port 3000 สำหรับ Next.js
EXPOSE 80

# คำสั่งรันแอป
CMD ["npm" , "start"]
