services:
  nextjs-app:
    image: nextjs-app
    container_name: nextjs-app
    build:
      context: .
    ports:
      - '4200:4200'
    volumes:
      - ./:/app
      - node_modules:/node_modules 

volumes:
  node_modules:
