services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env  # ใช้ไฟล์ .env
    environment:
      - NODE_ENV=production
      - APP_PORT=${APP_PORT}
    restart: always