services:
  nextjs-app:
    image: nextjs-app
    container_name: nextjs-app
    build:
      context: .
    ports:
      - '4200:4200'
    volumes:
      - node_modules:/node_modules 
      - build:/.next 
    command: >
      sh -c "yarn build && yarn start -p 4200"

volumes:
  node_modules:
  build:
