# ใช้ base image ที่มี Node.js 22.11.0
FROM node:22.11.0-alpine AS builder

# ตั้งค่า working directory
WORKDIR /app

# คัดลอกไฟล์ package.json และ package-lock.json
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm install

# คัดลอกโค้ดทั้งหมดเข้าไปใน container
COPY . .

# Build โปรเจค Next.js
RUN npm run dev

# ใช้ image ขนาดเล็กสำหรับ production
FROM node:22.11.0-alpine AS runner
WORKDIR /app

# คัดลอกไฟล์ที่จำเป็นจาก builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

# เปิดพอร์ต
EXPOSE 3000

# กำหนดคำสั่งเริ่มต้นเมื่อ container เริ่มทำงาน
CMD ["npm", "start"]